export default [
  { id: 0, State: '' },
  { id: '1', State: 'Abia' },
  { id: '2', State: 'Adamawa' },
  { id: '3', State: 'Akwa Ibom' },
  { id: '4', State: 'Anambra' },
  { id: '5', State: 'Bauchi' },
  { id: '6', State: 'Bayelsa' },
  { id: '7', State: 'Benue' },
  { id: '8', State: 'Borno' },
  { id: '9', State: 'Cross River' },
  { id: '10', State: 'Delta' },
  { id: '11', State: 'Ebonyi' },
  { id: '12', State: 'Edo' },
  { id: '13', State: 'Ekiti' },
  { id: '14', State: 'Enugu' },
  { id: '15', State: 'FCT - Abuja' },
  { id: '16', State: 'Gombe' },
  { id: '17', State: 'Imo' },
  { id: '18', State: 'Jigawa' },
  { id: '19', State: 'Kaduna' },
  { id: '20', State: 'Kano' },
  { id: '21', State: 'Katsina' },
  { id: '22', State: 'Kebbi' },
  { id: '23', State: 'Kogi' },
  { id: '24', State: 'Kwara' },
  { id: '25', State: 'Lagos' },
  { id: '26', State: 'Nasarawa' },
  { id: '27', State: 'Niger' },
  { id: '28', State: 'Ogun' },
  { id: '29', State: 'Ondo' },
  { id: '30', State: 'Osun' },
  { id: '31', State: 'Oyo' },
  { id: '32', State: 'Plateau' },
  { id: '33', State: 'Rivers' },
  { id: '34', State: 'Sokoto' },
  { id: '35', State: 'Taraba' },
  { id: '36', State: 'Yobe' },
  { id: '37', State: 'Zamfara' }
];
